<!DOCTYPE html>
<html lang="<?= substr(locale_get_default(), 0, 2) ?>">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>OpenExplorer</title>
        <link rel="stylesheet" href="public/stylesheets/normalize.css" type="text/css">
        <link rel="stylesheet" href="public/stylesheets/generalstyles.css" type="text/css">
    </head>